// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_passport.proto

package ru.kodos.almaz2.domain_objects;

public final class UserPassportClass {
    private UserPassportClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface UserPassportOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional uint32 passport_id = 1;

        /**
         * <code>optional uint32 passport_id = 1;</code>
         */
        boolean hasPassportId();

        /**
         * <code>optional uint32 passport_id = 1;</code>
         */
        int getPassportId();

        // optional string passport_type_id = 2;

        /**
         * <code>optional string passport_type_id = 2;</code>
         * <p/>
         * <pre>
         * id �������� ���� ����������
         * </pre>
         */
        boolean hasPassportTypeId();

        /**
         * <code>optional string passport_type_id = 2;</code>
         * <p/>
         * <pre>
         * id �������� ���� ����������
         * </pre>
         */
        java.lang.String getPassportTypeId();

        /**
         * <code>optional string passport_type_id = 2;</code>
         * <p/>
         * <pre>
         * id �������� ���� ����������
         * </pre>
         */
        com.google.protobuf.ByteString
        getPassportTypeIdBytes();

        // optional string login = 4;

        /**
         * <code>optional string login = 4;</code>
         */
        boolean hasLogin();

        /**
         * <code>optional string login = 4;</code>
         */
        java.lang.String getLogin();

        /**
         * <code>optional string login = 4;</code>
         */
        com.google.protobuf.ByteString
        getLoginBytes();

        // optional string password = 5;

        /**
         * <code>optional string password = 5;</code>
         */
        boolean hasPassword();

        /**
         * <code>optional string password = 5;</code>
         */
        java.lang.String getPassword();

        /**
         * <code>optional string password = 5;</code>
         */
        com.google.protobuf.ByteString
        getPasswordBytes();

        // optional .almaz2.domain_objects.MultiLanguageString display_name = 6;

        /**
         * <code>optional .almaz2.domain_objects.MultiLanguageString display_name = 6;</code>
         */
        boolean hasDisplayName();

        /**
         * <code>optional .almaz2.domain_objects.MultiLanguageString display_name = 6;</code>
         */
        ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString getDisplayName();

        /**
         * <code>optional .almaz2.domain_objects.MultiLanguageString display_name = 6;</code>
         */
        ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageStringOrBuilder getDisplayNameOrBuilder();
    }

    /**
     * Protobuf type {@code almaz2.domain_objects.UserPassport}
     */
    public static final class UserPassport extends
            com.google.protobuf.GeneratedMessage
            implements UserPassportOrBuilder {
        // Use UserPassport.newBuilder() to construct.
        private UserPassport(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private UserPassport(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final UserPassport defaultInstance;

        public static UserPassport getDefaultInstance() {
            return defaultInstance;
        }

        public UserPassport getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private UserPassport(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            passportId_ = input.readUInt32();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            passportTypeId_ = input.readBytes();
                            break;
                        }
                        case 34: {
                            bitField0_ |= 0x00000004;
                            login_ = input.readBytes();
                            break;
                        }
                        case 42: {
                            bitField0_ |= 0x00000008;
                            password_ = input.readBytes();
                            break;
                        }
                        case 50: {
                            ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString.Builder subBuilder = null;
                            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                                subBuilder = displayName_.toBuilder();
                            }
                            displayName_ = input.readMessage(ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString.PARSER, extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(displayName_);
                                displayName_ = subBuilder.buildPartial();
                            }
                            bitField0_ |= 0x00000010;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ru.kodos.almaz2.domain_objects.UserPassportClass.internal_static_almaz2_domain_objects_UserPassport_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ru.kodos.almaz2.domain_objects.UserPassportClass.internal_static_almaz2_domain_objects_UserPassport_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport.class, ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport.Builder.class);
        }

        public static com.google.protobuf.Parser<UserPassport> PARSER =
                new com.google.protobuf.AbstractParser<UserPassport>() {
                    public UserPassport parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new UserPassport(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<UserPassport> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        // optional uint32 passport_id = 1;
        public static final int PASSPORT_ID_FIELD_NUMBER = 1;
        private int passportId_;

        /**
         * <code>optional uint32 passport_id = 1;</code>
         */
        public boolean hasPassportId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional uint32 passport_id = 1;</code>
         */
        public int getPassportId() {
            return passportId_;
        }

        // optional string passport_type_id = 2;
        public static final int PASSPORT_TYPE_ID_FIELD_NUMBER = 2;
        private java.lang.Object passportTypeId_;

        /**
         * <code>optional string passport_type_id = 2;</code>
         * <p/>
         * <pre>
         * id �������� ���� ����������
         * </pre>
         */
        public boolean hasPassportTypeId() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional string passport_type_id = 2;</code>
         * <p/>
         * <pre>
         * id �������� ���� ����������
         * </pre>
         */
        public java.lang.String getPassportTypeId() {
            java.lang.Object ref = passportTypeId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    passportTypeId_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string passport_type_id = 2;</code>
         * <p/>
         * <pre>
         * id �������� ���� ����������
         * </pre>
         */
        public com.google.protobuf.ByteString
        getPassportTypeIdBytes() {
            java.lang.Object ref = passportTypeId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                passportTypeId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string login = 4;
        public static final int LOGIN_FIELD_NUMBER = 4;
        private java.lang.Object login_;

        /**
         * <code>optional string login = 4;</code>
         */
        public boolean hasLogin() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional string login = 4;</code>
         */
        public java.lang.String getLogin() {
            java.lang.Object ref = login_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    login_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string login = 4;</code>
         */
        public com.google.protobuf.ByteString
        getLoginBytes() {
            java.lang.Object ref = login_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                login_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string password = 5;
        public static final int PASSWORD_FIELD_NUMBER = 5;
        private java.lang.Object password_;

        /**
         * <code>optional string password = 5;</code>
         */
        public boolean hasPassword() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>optional string password = 5;</code>
         */
        public java.lang.String getPassword() {
            java.lang.Object ref = password_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    password_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string password = 5;</code>
         */
        public com.google.protobuf.ByteString
        getPasswordBytes() {
            java.lang.Object ref = password_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                password_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional .almaz2.domain_objects.MultiLanguageString display_name = 6;
        public static final int DISPLAY_NAME_FIELD_NUMBER = 6;
        private ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString displayName_;

        /**
         * <code>optional .almaz2.domain_objects.MultiLanguageString display_name = 6;</code>
         */
        public boolean hasDisplayName() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        /**
         * <code>optional .almaz2.domain_objects.MultiLanguageString display_name = 6;</code>
         */
        public ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString getDisplayName() {
            return displayName_;
        }

        /**
         * <code>optional .almaz2.domain_objects.MultiLanguageString display_name = 6;</code>
         */
        public ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageStringOrBuilder getDisplayNameOrBuilder() {
            return displayName_;
        }

        private void initFields() {
            passportId_ = 0;
            passportTypeId_ = "";
            login_ = "";
            password_ = "";
            displayName_ = ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString.getDefaultInstance();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (hasDisplayName()) {
                if (!getDisplayName().isInitialized()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeUInt32(1, passportId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getPassportTypeIdBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(4, getLoginBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeBytes(5, getPasswordBytes());
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeMessage(6, displayName_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(1, passportId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getPassportTypeIdBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, getLoginBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(5, getPasswordBytes());
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(6, displayName_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code almaz2.domain_objects.UserPassport}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassportOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ru.kodos.almaz2.domain_objects.UserPassportClass.internal_static_almaz2_domain_objects_UserPassport_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ru.kodos.almaz2.domain_objects.UserPassportClass.internal_static_almaz2_domain_objects_UserPassport_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport.class, ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport.Builder.class);
            }

            // Construct using ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getDisplayNameFieldBuilder();
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                passportId_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                passportTypeId_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                login_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                password_ = "";
                bitField0_ = (bitField0_ & ~0x00000008);
                if (displayNameBuilder_ == null) {
                    displayName_ = ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString.getDefaultInstance();
                } else {
                    displayNameBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000010);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ru.kodos.almaz2.domain_objects.UserPassportClass.internal_static_almaz2_domain_objects_UserPassport_descriptor;
            }

            public ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport getDefaultInstanceForType() {
                return ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport.getDefaultInstance();
            }

            public ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport build() {
                ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport buildPartial() {
                ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport result = new ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.passportId_ = passportId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.passportTypeId_ = passportTypeId_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.login_ = login_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.password_ = password_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                if (displayNameBuilder_ == null) {
                    result.displayName_ = displayName_;
                } else {
                    result.displayName_ = displayNameBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport) {
                    return mergeFrom((ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport other) {
                if (other == ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport.getDefaultInstance())
                    return this;
                if (other.hasPassportId()) {
                    setPassportId(other.getPassportId());
                }
                if (other.hasPassportTypeId()) {
                    bitField0_ |= 0x00000002;
                    passportTypeId_ = other.passportTypeId_;
                    onChanged();
                }
                if (other.hasLogin()) {
                    bitField0_ |= 0x00000004;
                    login_ = other.login_;
                    onChanged();
                }
                if (other.hasPassword()) {
                    bitField0_ |= 0x00000008;
                    password_ = other.password_;
                    onChanged();
                }
                if (other.hasDisplayName()) {
                    mergeDisplayName(other.getDisplayName());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (hasDisplayName()) {
                    if (!getDisplayName().isInitialized()) {

                        return false;
                    }
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ru.kodos.almaz2.domain_objects.UserPassportClass.UserPassport) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            // optional uint32 passport_id = 1;
            private int passportId_;

            /**
             * <code>optional uint32 passport_id = 1;</code>
             */
            public boolean hasPassportId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional uint32 passport_id = 1;</code>
             */
            public int getPassportId() {
                return passportId_;
            }

            /**
             * <code>optional uint32 passport_id = 1;</code>
             */
            public Builder setPassportId(int value) {
                bitField0_ |= 0x00000001;
                passportId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint32 passport_id = 1;</code>
             */
            public Builder clearPassportId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                passportId_ = 0;
                onChanged();
                return this;
            }

            // optional string passport_type_id = 2;
            private java.lang.Object passportTypeId_ = "";

            /**
             * <code>optional string passport_type_id = 2;</code>
             * <p/>
             * <pre>
             * id �������� ���� ����������
             * </pre>
             */
            public boolean hasPassportTypeId() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional string passport_type_id = 2;</code>
             * <p/>
             * <pre>
             * id �������� ���� ����������
             * </pre>
             */
            public java.lang.String getPassportTypeId() {
                java.lang.Object ref = passportTypeId_;
                if (!(ref instanceof java.lang.String)) {
                    java.lang.String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    passportTypeId_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string passport_type_id = 2;</code>
             * <p/>
             * <pre>
             * id �������� ���� ����������
             * </pre>
             */
            public com.google.protobuf.ByteString
            getPassportTypeIdBytes() {
                java.lang.Object ref = passportTypeId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    passportTypeId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string passport_type_id = 2;</code>
             * <p/>
             * <pre>
             * id �������� ���� ����������
             * </pre>
             */
            public Builder setPassportTypeId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                passportTypeId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string passport_type_id = 2;</code>
             * <p/>
             * <pre>
             * id �������� ���� ����������
             * </pre>
             */
            public Builder clearPassportTypeId() {
                bitField0_ = (bitField0_ & ~0x00000002);
                passportTypeId_ = getDefaultInstance().getPassportTypeId();
                onChanged();
                return this;
            }

            /**
             * <code>optional string passport_type_id = 2;</code>
             * <p/>
             * <pre>
             * id �������� ���� ����������
             * </pre>
             */
            public Builder setPassportTypeIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                passportTypeId_ = value;
                onChanged();
                return this;
            }

            // optional string login = 4;
            private java.lang.Object login_ = "";

            /**
             * <code>optional string login = 4;</code>
             */
            public boolean hasLogin() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional string login = 4;</code>
             */
            public java.lang.String getLogin() {
                java.lang.Object ref = login_;
                if (!(ref instanceof java.lang.String)) {
                    java.lang.String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    login_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string login = 4;</code>
             */
            public com.google.protobuf.ByteString
            getLoginBytes() {
                java.lang.Object ref = login_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    login_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string login = 4;</code>
             */
            public Builder setLogin(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                login_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string login = 4;</code>
             */
            public Builder clearLogin() {
                bitField0_ = (bitField0_ & ~0x00000004);
                login_ = getDefaultInstance().getLogin();
                onChanged();
                return this;
            }

            /**
             * <code>optional string login = 4;</code>
             */
            public Builder setLoginBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                login_ = value;
                onChanged();
                return this;
            }

            // optional string password = 5;
            private java.lang.Object password_ = "";

            /**
             * <code>optional string password = 5;</code>
             */
            public boolean hasPassword() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>optional string password = 5;</code>
             */
            public java.lang.String getPassword() {
                java.lang.Object ref = password_;
                if (!(ref instanceof java.lang.String)) {
                    java.lang.String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    password_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string password = 5;</code>
             */
            public com.google.protobuf.ByteString
            getPasswordBytes() {
                java.lang.Object ref = password_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    password_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string password = 5;</code>
             */
            public Builder setPassword(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                password_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string password = 5;</code>
             */
            public Builder clearPassword() {
                bitField0_ = (bitField0_ & ~0x00000008);
                password_ = getDefaultInstance().getPassword();
                onChanged();
                return this;
            }

            /**
             * <code>optional string password = 5;</code>
             */
            public Builder setPasswordBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                password_ = value;
                onChanged();
                return this;
            }

            // optional .almaz2.domain_objects.MultiLanguageString display_name = 6;
            private ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString displayName_ = ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString.getDefaultInstance();
            private com.google.protobuf.SingleFieldBuilder<
                    ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString, ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString.Builder, ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageStringOrBuilder> displayNameBuilder_;

            /**
             * <code>optional .almaz2.domain_objects.MultiLanguageString display_name = 6;</code>
             */
            public boolean hasDisplayName() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            /**
             * <code>optional .almaz2.domain_objects.MultiLanguageString display_name = 6;</code>
             */
            public ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString getDisplayName() {
                if (displayNameBuilder_ == null) {
                    return displayName_;
                } else {
                    return displayNameBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .almaz2.domain_objects.MultiLanguageString display_name = 6;</code>
             */
            public Builder setDisplayName(ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString value) {
                if (displayNameBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    displayName_ = value;
                    onChanged();
                } else {
                    displayNameBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000010;
                return this;
            }

            /**
             * <code>optional .almaz2.domain_objects.MultiLanguageString display_name = 6;</code>
             */
            public Builder setDisplayName(
                    ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString.Builder builderForValue) {
                if (displayNameBuilder_ == null) {
                    displayName_ = builderForValue.build();
                    onChanged();
                } else {
                    displayNameBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000010;
                return this;
            }

            /**
             * <code>optional .almaz2.domain_objects.MultiLanguageString display_name = 6;</code>
             */
            public Builder mergeDisplayName(ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString value) {
                if (displayNameBuilder_ == null) {
                    if (((bitField0_ & 0x00000010) == 0x00000010) &&
                            displayName_ != ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString.getDefaultInstance()) {
                        displayName_ =
                                ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString.newBuilder(displayName_).mergeFrom(value).buildPartial();
                    } else {
                        displayName_ = value;
                    }
                    onChanged();
                } else {
                    displayNameBuilder_.mergeFrom(value);
                }
                bitField0_ |= 0x00000010;
                return this;
            }

            /**
             * <code>optional .almaz2.domain_objects.MultiLanguageString display_name = 6;</code>
             */
            public Builder clearDisplayName() {
                if (displayNameBuilder_ == null) {
                    displayName_ = ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString.getDefaultInstance();
                    onChanged();
                } else {
                    displayNameBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000010);
                return this;
            }

            /**
             * <code>optional .almaz2.domain_objects.MultiLanguageString display_name = 6;</code>
             */
            public ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString.Builder getDisplayNameBuilder() {
                bitField0_ |= 0x00000010;
                onChanged();
                return getDisplayNameFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .almaz2.domain_objects.MultiLanguageString display_name = 6;</code>
             */
            public ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageStringOrBuilder getDisplayNameOrBuilder() {
                if (displayNameBuilder_ != null) {
                    return displayNameBuilder_.getMessageOrBuilder();
                } else {
                    return displayName_;
                }
            }

            /**
             * <code>optional .almaz2.domain_objects.MultiLanguageString display_name = 6;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<
                    ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString, ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString.Builder, ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageStringOrBuilder>
            getDisplayNameFieldBuilder() {
                if (displayNameBuilder_ == null) {
                    displayNameBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString, ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageString.Builder, ru.kodos.almaz2.domain_objects.FieldTypesClass.MultiLanguageStringOrBuilder>(
                            displayName_,
                            getParentForChildren(),
                            isClean());
                    displayName_ = null;
                }
                return displayNameBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:almaz2.domain_objects.UserPassport)
        }

        static {
            defaultInstance = new UserPassport(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:almaz2.domain_objects.UserPassport)
    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_almaz2_domain_objects_UserPassport_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_almaz2_domain_objects_UserPassport_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\023user_passport.proto\022\025almaz2.domain_obj" +
                        "ects\032\021field_types.proto\"\240\001\n\014UserPassport" +
                        "\022\023\n\013passport_id\030\001 \001(\r\022\030\n\020passport_type_i" +
                        "d\030\002 \001(\t\022\r\n\005login\030\004 \001(\t\022\020\n\010password\030\005 \001(\t" +
                        "\022@\n\014display_name\030\006 \001(\0132*.almaz2.domain_o" +
                        "bjects.MultiLanguageStringB3\n\036ru.kodos.a" +
                        "lmaz2.domain_objectsB\021UserPassportClass"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_almaz2_domain_objects_UserPassport_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_almaz2_domain_objects_UserPassport_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_almaz2_domain_objects_UserPassport_descriptor,
                                new java.lang.String[]{"PassportId", "PassportTypeId", "Login", "Password", "DisplayName",});
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                ru.kodos.almaz2.domain_objects.FieldTypesClass.getDescriptor(),
                        }, assigner
                );
    }

    // @@protoc_insertion_point(outer_class_scope)
}
