D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./control_element_passport_type.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./control_object_passport.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./control_object_passport_type.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./control_object_equipment.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./equipment_passport_type.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./equipment_passport.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./equipment_firmware_passport.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./equipment_logical_input_passport_type.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./equipment_logical_output_passport_type.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./field_types.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./managed_element_passport_type.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./properties.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./reference.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./sensor_passport_type.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./rpc.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./interface_passport_type.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./interface_passport.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./conversion_formula.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./periodic_signal.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./control_object_state.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./statuses.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./statistics.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./zone.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./control_object_alarm.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./client_passport.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./user_passport.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./database_commands.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./equipment_commands.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./control_object_commands.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./action_commands.proto
D:\etc\protoc\protoc.exe -I=./ --java_out=..\src ./control_object_change_over_period.proto
pause