// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: action_commands.proto

package ru.kodos.almaz2.rpc.commands;

public final class ActionCommandsClass {
  private ActionCommandsClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AlarmActionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 id = 1;
    /**
     * <code>optional uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional uint32 id = 1;</code>
     */
    int getId();

    // optional uint32 alarm_id = 2;
    /**
     * <code>optional uint32 alarm_id = 2;</code>
     */
    boolean hasAlarmId();
    /**
     * <code>optional uint32 alarm_id = 2;</code>
     */
    int getAlarmId();

    // optional uint32 control_object_id = 3;
    /**
     * <code>optional uint32 control_object_id = 3;</code>
     */
    boolean hasControlObjectId();
    /**
     * <code>optional uint32 control_object_id = 3;</code>
     */
    int getControlObjectId();

    // optional uint32 time = 4;
    /**
     * <code>optional uint32 time = 4;</code>
     */
    boolean hasTime();
    /**
     * <code>optional uint32 time = 4;</code>
     */
    int getTime();

    // optional .almaz2.rpc.commands.AlarmAction.ActionType type = 5 [default = PROCESS_UNKNOWN];
    /**
     * <code>optional .almaz2.rpc.commands.AlarmAction.ActionType type = 5 [default = PROCESS_UNKNOWN];</code>
     */
    boolean hasType();
    /**
     * <code>optional .almaz2.rpc.commands.AlarmAction.ActionType type = 5 [default = PROCESS_UNKNOWN];</code>
     */
    ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.ActionType getType();

    // optional bool action_sended = 6;
    /**
     * <code>optional bool action_sended = 6;</code>
     */
    boolean hasActionSended();
    /**
     * <code>optional bool action_sended = 6;</code>
     */
    boolean getActionSended();

    // optional string remark = 7;
    /**
     * <code>optional string remark = 7;</code>
     */
    boolean hasRemark();
    /**
     * <code>optional string remark = 7;</code>
     */
    java.lang.String getRemark();
    /**
     * <code>optional string remark = 7;</code>
     */
    com.google.protobuf.ByteString
        getRemarkBytes();
  }
  /**
   * Protobuf type {@code almaz2.rpc.commands.AlarmAction}
   *
   * <pre>
   **
   * Действие над тревогой
   * </pre>
   */
  public static final class AlarmAction extends
      com.google.protobuf.GeneratedMessage
      implements AlarmActionOrBuilder {
    // Use AlarmAction.newBuilder() to construct.
    private AlarmAction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AlarmAction(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AlarmAction defaultInstance;
    public static AlarmAction getDefaultInstance() {
      return defaultInstance;
    }

    public AlarmAction getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AlarmAction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              alarmId_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              controlObjectId_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              time_ = input.readUInt32();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.ActionType value = ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.ActionType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                type_ = value;
              }
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              actionSended_ = input.readBool();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              remark_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.internal_static_almaz2_rpc_commands_AlarmAction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.internal_static_almaz2_rpc_commands_AlarmAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.class, ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.Builder.class);
    }

    public static com.google.protobuf.Parser<AlarmAction> PARSER =
        new com.google.protobuf.AbstractParser<AlarmAction>() {
      public AlarmAction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AlarmAction(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AlarmAction> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code almaz2.rpc.commands.AlarmAction.ActionType}
     */
    public enum ActionType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PROCESS_UNKNOWN = 0;</code>
       */
      PROCESS_UNKNOWN(0, 0),
      /**
       * <code>PROCESS_BEGIN = 1;</code>
       */
      PROCESS_BEGIN(1, 1),
      /**
       * <code>PROCESS_FINISH = 2;</code>
       */
      PROCESS_FINISH(2, 2),
      ;

      /**
       * <code>PROCESS_UNKNOWN = 0;</code>
       */
      public static final int PROCESS_UNKNOWN_VALUE = 0;
      /**
       * <code>PROCESS_BEGIN = 1;</code>
       */
      public static final int PROCESS_BEGIN_VALUE = 1;
      /**
       * <code>PROCESS_FINISH = 2;</code>
       */
      public static final int PROCESS_FINISH_VALUE = 2;


      public final int getNumber() { return value; }

      public static ActionType valueOf(int value) {
        switch (value) {
          case 0: return PROCESS_UNKNOWN;
          case 1: return PROCESS_BEGIN;
          case 2: return PROCESS_FINISH;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ActionType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ActionType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ActionType>() {
              public ActionType findValueByNumber(int number) {
                return ActionType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.getDescriptor().getEnumTypes().get(0);
      }

      private static final ActionType[] VALUES = values();

      public static ActionType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ActionType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:almaz2.rpc.commands.AlarmAction.ActionType)
    }

    private int bitField0_;
    // optional uint32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // optional uint32 alarm_id = 2;
    public static final int ALARM_ID_FIELD_NUMBER = 2;
    private int alarmId_;
    /**
     * <code>optional uint32 alarm_id = 2;</code>
     */
    public boolean hasAlarmId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 alarm_id = 2;</code>
     */
    public int getAlarmId() {
      return alarmId_;
    }

    // optional uint32 control_object_id = 3;
    public static final int CONTROL_OBJECT_ID_FIELD_NUMBER = 3;
    private int controlObjectId_;
    /**
     * <code>optional uint32 control_object_id = 3;</code>
     */
    public boolean hasControlObjectId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 control_object_id = 3;</code>
     */
    public int getControlObjectId() {
      return controlObjectId_;
    }

    // optional uint32 time = 4;
    public static final int TIME_FIELD_NUMBER = 4;
    private int time_;
    /**
     * <code>optional uint32 time = 4;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 time = 4;</code>
     */
    public int getTime() {
      return time_;
    }

    // optional .almaz2.rpc.commands.AlarmAction.ActionType type = 5 [default = PROCESS_UNKNOWN];
    public static final int TYPE_FIELD_NUMBER = 5;
    private ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.ActionType type_;
    /**
     * <code>optional .almaz2.rpc.commands.AlarmAction.ActionType type = 5 [default = PROCESS_UNKNOWN];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .almaz2.rpc.commands.AlarmAction.ActionType type = 5 [default = PROCESS_UNKNOWN];</code>
     */
    public ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.ActionType getType() {
      return type_;
    }

    // optional bool action_sended = 6;
    public static final int ACTION_SENDED_FIELD_NUMBER = 6;
    private boolean actionSended_;
    /**
     * <code>optional bool action_sended = 6;</code>
     */
    public boolean hasActionSended() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool action_sended = 6;</code>
     */
    public boolean getActionSended() {
      return actionSended_;
    }

    // optional string remark = 7;
    public static final int REMARK_FIELD_NUMBER = 7;
    private java.lang.Object remark_;
    /**
     * <code>optional string remark = 7;</code>
     */
    public boolean hasRemark() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string remark = 7;</code>
     */
    public java.lang.String getRemark() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          remark_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string remark = 7;</code>
     */
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0;
      alarmId_ = 0;
      controlObjectId_ = 0;
      time_ = 0;
      type_ = ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.ActionType.PROCESS_UNKNOWN;
      actionSended_ = false;
      remark_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, alarmId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, controlObjectId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, time_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, type_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, actionSended_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getRemarkBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, alarmId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, controlObjectId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, time_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, type_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, actionSended_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getRemarkBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code almaz2.rpc.commands.AlarmAction}
     *
     * <pre>
     **
     * Действие над тревогой
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.internal_static_almaz2_rpc_commands_AlarmAction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.internal_static_almaz2_rpc_commands_AlarmAction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.class, ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.Builder.class);
      }

      // Construct using ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        alarmId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        controlObjectId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.ActionType.PROCESS_UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000010);
        actionSended_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        remark_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.internal_static_almaz2_rpc_commands_AlarmAction_descriptor;
      }

      public ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction getDefaultInstanceForType() {
        return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.getDefaultInstance();
      }

      public ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction build() {
        ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction buildPartial() {
        ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction result = new ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.alarmId_ = alarmId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.controlObjectId_ = controlObjectId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.actionSended_ = actionSended_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.remark_ = remark_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction) {
          return mergeFrom((ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction other) {
        if (other == ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAlarmId()) {
          setAlarmId(other.getAlarmId());
        }
        if (other.hasControlObjectId()) {
          setControlObjectId(other.getControlObjectId());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasActionSended()) {
          setActionSended(other.getActionSended());
        }
        if (other.hasRemark()) {
          bitField0_ |= 0x00000040;
          remark_ = other.remark_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 id = 1;
      private int id_ ;
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 alarm_id = 2;
      private int alarmId_ ;
      /**
       * <code>optional uint32 alarm_id = 2;</code>
       */
      public boolean hasAlarmId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 alarm_id = 2;</code>
       */
      public int getAlarmId() {
        return alarmId_;
      }
      /**
       * <code>optional uint32 alarm_id = 2;</code>
       */
      public Builder setAlarmId(int value) {
        bitField0_ |= 0x00000002;
        alarmId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 alarm_id = 2;</code>
       */
      public Builder clearAlarmId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        alarmId_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 control_object_id = 3;
      private int controlObjectId_ ;
      /**
       * <code>optional uint32 control_object_id = 3;</code>
       */
      public boolean hasControlObjectId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 control_object_id = 3;</code>
       */
      public int getControlObjectId() {
        return controlObjectId_;
      }
      /**
       * <code>optional uint32 control_object_id = 3;</code>
       */
      public Builder setControlObjectId(int value) {
        bitField0_ |= 0x00000004;
        controlObjectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 control_object_id = 3;</code>
       */
      public Builder clearControlObjectId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        controlObjectId_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 time = 4;
      private int time_ ;
      /**
       * <code>optional uint32 time = 4;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 time = 4;</code>
       */
      public int getTime() {
        return time_;
      }
      /**
       * <code>optional uint32 time = 4;</code>
       */
      public Builder setTime(int value) {
        bitField0_ |= 0x00000008;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 time = 4;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        time_ = 0;
        onChanged();
        return this;
      }

      // optional .almaz2.rpc.commands.AlarmAction.ActionType type = 5 [default = PROCESS_UNKNOWN];
      private ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.ActionType type_ = ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.ActionType.PROCESS_UNKNOWN;
      /**
       * <code>optional .almaz2.rpc.commands.AlarmAction.ActionType type = 5 [default = PROCESS_UNKNOWN];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .almaz2.rpc.commands.AlarmAction.ActionType type = 5 [default = PROCESS_UNKNOWN];</code>
       */
      public ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.ActionType getType() {
        return type_;
      }
      /**
       * <code>optional .almaz2.rpc.commands.AlarmAction.ActionType type = 5 [default = PROCESS_UNKNOWN];</code>
       */
      public Builder setType(ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.ActionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .almaz2.rpc.commands.AlarmAction.ActionType type = 5 [default = PROCESS_UNKNOWN];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.ActionType.PROCESS_UNKNOWN;
        onChanged();
        return this;
      }

      // optional bool action_sended = 6;
      private boolean actionSended_ ;
      /**
       * <code>optional bool action_sended = 6;</code>
       */
      public boolean hasActionSended() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bool action_sended = 6;</code>
       */
      public boolean getActionSended() {
        return actionSended_;
      }
      /**
       * <code>optional bool action_sended = 6;</code>
       */
      public Builder setActionSended(boolean value) {
        bitField0_ |= 0x00000020;
        actionSended_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool action_sended = 6;</code>
       */
      public Builder clearActionSended() {
        bitField0_ = (bitField0_ & ~0x00000020);
        actionSended_ = false;
        onChanged();
        return this;
      }

      // optional string remark = 7;
      private java.lang.Object remark_ = "";
      /**
       * <code>optional string remark = 7;</code>
       */
      public boolean hasRemark() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string remark = 7;</code>
       */
      public java.lang.String getRemark() {
        java.lang.Object ref = remark_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          remark_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string remark = 7;</code>
       */
      public com.google.protobuf.ByteString
          getRemarkBytes() {
        java.lang.Object ref = remark_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remark_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string remark = 7;</code>
       */
      public Builder setRemark(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        remark_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string remark = 7;</code>
       */
      public Builder clearRemark() {
        bitField0_ = (bitField0_ & ~0x00000040);
        remark_ = getDefaultInstance().getRemark();
        onChanged();
        return this;
      }
      /**
       * <code>optional string remark = 7;</code>
       */
      public Builder setRemarkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        remark_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:almaz2.rpc.commands.AlarmAction)
    }

    static {
      defaultInstance = new AlarmAction(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:almaz2.rpc.commands.AlarmAction)
  }

  public interface ActionCommandBaseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 id = 1;
    /**
     * <code>optional uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional uint32 id = 1;</code>
     */
    int getId();

    // optional .almaz2.rpc.commands.AlarmAction action_alarm = 2;
    /**
     * <code>optional .almaz2.rpc.commands.AlarmAction action_alarm = 2;</code>
     */
    boolean hasActionAlarm();
    /**
     * <code>optional .almaz2.rpc.commands.AlarmAction action_alarm = 2;</code>
     */
    ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction getActionAlarm();
    /**
     * <code>optional .almaz2.rpc.commands.AlarmAction action_alarm = 2;</code>
     */
    ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmActionOrBuilder getActionAlarmOrBuilder();
  }
  /**
   * Protobuf type {@code almaz2.rpc.commands.ActionCommandBase}
   *
   * <pre>
   **
   * Базовое сообщение действия
   * </pre>
   */
  public static final class ActionCommandBase extends
      com.google.protobuf.GeneratedMessage
      implements ActionCommandBaseOrBuilder {
    // Use ActionCommandBase.newBuilder() to construct.
    private ActionCommandBase(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ActionCommandBase(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ActionCommandBase defaultInstance;
    public static ActionCommandBase getDefaultInstance() {
      return defaultInstance;
    }

    public ActionCommandBase getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ActionCommandBase(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 18: {
              ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = actionAlarm_.toBuilder();
              }
              actionAlarm_ = input.readMessage(ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(actionAlarm_);
                actionAlarm_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.internal_static_almaz2_rpc_commands_ActionCommandBase_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.internal_static_almaz2_rpc_commands_ActionCommandBase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase.class, ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase.Builder.class);
    }

    public static com.google.protobuf.Parser<ActionCommandBase> PARSER =
        new com.google.protobuf.AbstractParser<ActionCommandBase>() {
      public ActionCommandBase parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ActionCommandBase(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ActionCommandBase> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // optional .almaz2.rpc.commands.AlarmAction action_alarm = 2;
    public static final int ACTION_ALARM_FIELD_NUMBER = 2;
    private ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction actionAlarm_;
    /**
     * <code>optional .almaz2.rpc.commands.AlarmAction action_alarm = 2;</code>
     */
    public boolean hasActionAlarm() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .almaz2.rpc.commands.AlarmAction action_alarm = 2;</code>
     */
    public ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction getActionAlarm() {
      return actionAlarm_;
    }
    /**
     * <code>optional .almaz2.rpc.commands.AlarmAction action_alarm = 2;</code>
     */
    public ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmActionOrBuilder getActionAlarmOrBuilder() {
      return actionAlarm_;
    }

    private void initFields() {
      id_ = 0;
      actionAlarm_ = ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, actionAlarm_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, actionAlarm_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code almaz2.rpc.commands.ActionCommandBase}
     *
     * <pre>
     **
     * Базовое сообщение действия
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.internal_static_almaz2_rpc_commands_ActionCommandBase_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.internal_static_almaz2_rpc_commands_ActionCommandBase_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase.class, ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase.Builder.class);
      }

      // Construct using ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getActionAlarmFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (actionAlarmBuilder_ == null) {
          actionAlarm_ = ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.getDefaultInstance();
        } else {
          actionAlarmBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.internal_static_almaz2_rpc_commands_ActionCommandBase_descriptor;
      }

      public ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase getDefaultInstanceForType() {
        return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase.getDefaultInstance();
      }

      public ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase build() {
        ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase buildPartial() {
        ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase result = new ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (actionAlarmBuilder_ == null) {
          result.actionAlarm_ = actionAlarm_;
        } else {
          result.actionAlarm_ = actionAlarmBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase) {
          return mergeFrom((ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase other) {
        if (other == ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasActionAlarm()) {
          mergeActionAlarm(other.getActionAlarm());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionCommandBase) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 id = 1;
      private int id_ ;
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional .almaz2.rpc.commands.AlarmAction action_alarm = 2;
      private ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction actionAlarm_ = ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction, ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.Builder, ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmActionOrBuilder> actionAlarmBuilder_;
      /**
       * <code>optional .almaz2.rpc.commands.AlarmAction action_alarm = 2;</code>
       */
      public boolean hasActionAlarm() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .almaz2.rpc.commands.AlarmAction action_alarm = 2;</code>
       */
      public ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction getActionAlarm() {
        if (actionAlarmBuilder_ == null) {
          return actionAlarm_;
        } else {
          return actionAlarmBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .almaz2.rpc.commands.AlarmAction action_alarm = 2;</code>
       */
      public Builder setActionAlarm(ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction value) {
        if (actionAlarmBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          actionAlarm_ = value;
          onChanged();
        } else {
          actionAlarmBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .almaz2.rpc.commands.AlarmAction action_alarm = 2;</code>
       */
      public Builder setActionAlarm(
          ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.Builder builderForValue) {
        if (actionAlarmBuilder_ == null) {
          actionAlarm_ = builderForValue.build();
          onChanged();
        } else {
          actionAlarmBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .almaz2.rpc.commands.AlarmAction action_alarm = 2;</code>
       */
      public Builder mergeActionAlarm(ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction value) {
        if (actionAlarmBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              actionAlarm_ != ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.getDefaultInstance()) {
            actionAlarm_ =
              ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.newBuilder(actionAlarm_).mergeFrom(value).buildPartial();
          } else {
            actionAlarm_ = value;
          }
          onChanged();
        } else {
          actionAlarmBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .almaz2.rpc.commands.AlarmAction action_alarm = 2;</code>
       */
      public Builder clearActionAlarm() {
        if (actionAlarmBuilder_ == null) {
          actionAlarm_ = ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.getDefaultInstance();
          onChanged();
        } else {
          actionAlarmBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .almaz2.rpc.commands.AlarmAction action_alarm = 2;</code>
       */
      public ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.Builder getActionAlarmBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getActionAlarmFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .almaz2.rpc.commands.AlarmAction action_alarm = 2;</code>
       */
      public ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmActionOrBuilder getActionAlarmOrBuilder() {
        if (actionAlarmBuilder_ != null) {
          return actionAlarmBuilder_.getMessageOrBuilder();
        } else {
          return actionAlarm_;
        }
      }
      /**
       * <code>optional .almaz2.rpc.commands.AlarmAction action_alarm = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction, ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.Builder, ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmActionOrBuilder> 
          getActionAlarmFieldBuilder() {
        if (actionAlarmBuilder_ == null) {
          actionAlarmBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction, ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmAction.Builder, ru.kodos.almaz2.rpc.commands.ActionCommandsClass.AlarmActionOrBuilder>(
                  actionAlarm_,
                  getParentForChildren(),
                  isClean());
          actionAlarm_ = null;
        }
        return actionAlarmBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:almaz2.rpc.commands.ActionCommandBase)
    }

    static {
      defaultInstance = new ActionCommandBase(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:almaz2.rpc.commands.ActionCommandBase)
  }

  public interface ActionResultBaseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 id = 1;
    /**
     * <code>optional uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional uint32 id = 1;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code almaz2.rpc.commands.ActionResultBase}
   *
   * <pre>
   **
   * Базовое сообщение с результатом действия
   * </pre>
   */
  public static final class ActionResultBase extends
      com.google.protobuf.GeneratedMessage
      implements ActionResultBaseOrBuilder {
    // Use ActionResultBase.newBuilder() to construct.
    private ActionResultBase(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ActionResultBase(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ActionResultBase defaultInstance;
    public static ActionResultBase getDefaultInstance() {
      return defaultInstance;
    }

    public ActionResultBase getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ActionResultBase(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.internal_static_almaz2_rpc_commands_ActionResultBase_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.internal_static_almaz2_rpc_commands_ActionResultBase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase.class, ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase.Builder.class);
    }

    public static com.google.protobuf.Parser<ActionResultBase> PARSER =
        new com.google.protobuf.AbstractParser<ActionResultBase>() {
      public ActionResultBase parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ActionResultBase(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ActionResultBase> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    private void initFields() {
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code almaz2.rpc.commands.ActionResultBase}
     *
     * <pre>
     **
     * Базовое сообщение с результатом действия
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.internal_static_almaz2_rpc_commands_ActionResultBase_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.internal_static_almaz2_rpc_commands_ActionResultBase_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase.class, ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase.Builder.class);
      }

      // Construct using ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.internal_static_almaz2_rpc_commands_ActionResultBase_descriptor;
      }

      public ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase getDefaultInstanceForType() {
        return ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase.getDefaultInstance();
      }

      public ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase build() {
        ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase buildPartial() {
        ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase result = new ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase) {
          return mergeFrom((ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase other) {
        if (other == ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.kodos.almaz2.rpc.commands.ActionCommandsClass.ActionResultBase) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 id = 1;
      private int id_ ;
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:almaz2.rpc.commands.ActionResultBase)
    }

    static {
      defaultInstance = new ActionResultBase(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:almaz2.rpc.commands.ActionResultBase)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_almaz2_rpc_commands_AlarmAction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_almaz2_rpc_commands_AlarmAction_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_almaz2_rpc_commands_ActionCommandBase_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_almaz2_rpc_commands_ActionCommandBase_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_almaz2_rpc_commands_ActionResultBase_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_almaz2_rpc_commands_ActionResultBase_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025action_commands.proto\022\023almaz2.rpc.comm" +
      "ands\"\221\002\n\013AlarmAction\022\n\n\002id\030\001 \001(\r\022\020\n\010alar" +
      "m_id\030\002 \001(\r\022\031\n\021control_object_id\030\003 \001(\r\022\014\n" +
      "\004time\030\004 \001(\r\022J\n\004type\030\005 \001(\0162+.almaz2.rpc.c" +
      "ommands.AlarmAction.ActionType:\017PROCESS_" +
      "UNKNOWN\022\025\n\raction_sended\030\006 \001(\010\022\016\n\006remark" +
      "\030\007 \001(\t\"H\n\nActionType\022\023\n\017PROCESS_UNKNOWN\020" +
      "\000\022\021\n\rPROCESS_BEGIN\020\001\022\022\n\016PROCESS_FINISH\020\002" +
      "\"W\n\021ActionCommandBase\022\n\n\002id\030\001 \001(\r\0226\n\014act" +
      "ion_alarm\030\002 \001(\0132 .almaz2.rpc.commands.Al",
      "armAction\"\036\n\020ActionResultBase\022\n\n\002id\030\001 \001(" +
      "\rB3\n\034ru.kodos.almaz2.rpc.commandsB\023Actio" +
      "nCommandsClass"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_almaz2_rpc_commands_AlarmAction_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_almaz2_rpc_commands_AlarmAction_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_almaz2_rpc_commands_AlarmAction_descriptor,
              new java.lang.String[] { "Id", "AlarmId", "ControlObjectId", "Time", "Type", "ActionSended", "Remark", });
          internal_static_almaz2_rpc_commands_ActionCommandBase_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_almaz2_rpc_commands_ActionCommandBase_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_almaz2_rpc_commands_ActionCommandBase_descriptor,
              new java.lang.String[] { "Id", "ActionAlarm", });
          internal_static_almaz2_rpc_commands_ActionResultBase_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_almaz2_rpc_commands_ActionResultBase_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_almaz2_rpc_commands_ActionResultBase_descriptor,
              new java.lang.String[] { "Id", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
